drop table project_clean
CREATE TABLE  "PROJECT_CLEAN" 
   (	"PROJECT_SKID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"PLT_SHORT_DESC" VARCHAR2(500), 
	"PLT_REQUIRED_START_DATE" DATE, 
	"PLT_ESTIMATED_END_DATE" DATE, 
	"PLT_ACTUAL_START_DATE" DATE, 
	"PLT_ACTUAL_END_DATE" DATE, 
	"PLT_RENEWAL_NO" NUMBER(*,0), 
	"PLT_RATE_DAY_PROJ" VARCHAR2(100), 
	"ACTUAL_SALARY" NUMBER, 
	
	 CONSTRAINT "PK_PROJECT_CLEAN" PRIMARY KEY ("PROJECT_SKID") ENABLE
   );
----------------------------------------------------------------------

select * from staging_project 


drop table project_error;
CREATE TABLE  "PROJECT_ERROR" 
   (	"PROJECT_SKID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"PLT_SHORT_DESC" VARCHAR2(500), 
	"PLT_REQUIRED_START_DATE" DATE, 
	"PLT_ESTIMATED_END_DATE" DATE, 
	"PLT_ACTUAL_START_DATE" DATE, 
	"PLT_ACTUAL_END_DATE" DATE, 
	"PLT_RENEWAL_NO" NUMBER(*,0), 
	"PLT_RATE_DAY_PROJ" VARCHAR2(100), 
	"ACTUAL_SALARY" NUMBER, 
	
	 CONSTRAINT "PK_PROJECT_ERROR" PRIMARY KEY ("PROJECT_SKID") ENABLE
   );
