CREATE OR REPLACE PROCEDURE SPR_CLEAN_ERR_PROJECT
AS
CURSOR CUR IS
SELECT * FROM STG_PROJECT;

RES   STG_PROJECT%ROWTYPE;

BEGIN 
OPEN CUR ;
LOOP
FETCH CUR INTO RES;
EXIT WHEN CUR%NOTFOUND;

IF  REGEXP_LIKE(RES.plct_short_desc,'[*|_|#|$]' )  
THEN
INSERT INTO PROJECT_ERROR 
VALUES(
  res.project_key,--ACCOUNT_SKID OF ERROR
  RES.PROJECT_id_LDS,--ACCOUNT_ID OF ERROR
  RES.PROJECT_id_MCH,--ACCOUNT_ID OF ERROR
  RES.PLCT_SHORT_DESC, 
  RES.PLCT_REQUIRED_START_DATE , 
	RES.PLCT_ESTIMATED_END_DATE , 
	RES.PLCT_ACTUAL_START_DATE , 
	RES.PLCT_ACTUAL_END_DATE , 
	RES.PLCT_RENEWAL_NUMBER , 
	RES.PLCT_RATE_DAY_PROJ , 
	RES.ACTUAL_SALARY ,
  RES.ACCOUNT_ID_LDS,
  RES.ACCOUNT_ID_MCH,
	RES.CONSULTANT_ID_LDS,
	RES.CONSULTANT_ID_MCH
  );
  
INSERT INTO PRO_ISSUES
  (
  ISSUE_ID, 
  ROW_ID, 
  ISSUE, 
  i_STATUS)
VALUES(
  STAGING_PROJECT_SEQ.nextval, 
  RES.PROJECT_KEY, 
  'GARBAGE CHARACTERS FOUND ', 
  'UN-FIXED'
  );

ELSIF   RES.plct_short_desc IS NULL 
THEN
INSERT INTO PROJECT_ERROR 
VALUES(
   res.project_key,--ACCOUNT_SKID OF ERROR
   RES.PROJECT_id_LDS,--ACCOUNT_ID OF ERROR
  RES.PROJECT_id_MCH,
  RES.PLCT_SHORT_DESC, 
 RES.PLCT_REQUIRED_START_DATE , 
	RES.PLCT_ESTIMATED_END_DATE , 
	RES.PLCT_ACTUAL_START_DATE , 
	RES.PLCT_ACTUAL_END_DATE , 
	RES.PLCT_RENEWAL_NUMBER , 
	RES.PLCT_RATE_DAY_PROJ , 
	RES.ACTUAL_SALARY,  
  RES.ACCOUNT_ID_LDS,
  RES.ACCOUNT_ID_MCH,
	RES.CONSULTANT_ID_LDS,
	RES.CONSULTANT_ID_MCH
  );
  
INSERT INTO PRO_ISSUES
  (
  ISSUE_ID, 
  ROW_ID, 
  ISSUE, 
  i_STATUS)
VALUES(
  STAGING_PROJECT_SEQ.nextval, 
  RES.PROJECT_KEY, 
  'FOUND VALUES EMPTY', 
  'UN-FIXED'
  );
  
ELSE

INSERT INTO PROJECT_CLEAN 
VALUES(
    res.project_key,--ACCOUNT_SKID OF ERROR
   RES.PROJECT_id_LDS,--ACCOUNT_ID OF ERROR
  RES.PROJECT_id_MCH,
  RES.PLCT_SHORT_DESC, 
 RES.PLCT_REQUIRED_START_DATE , 
	RES.PLCT_ESTIMATED_END_DATE , 
	RES.PLCT_ACTUAL_START_DATE , 
	RES.PLCT_ACTUAL_END_DATE , 
	RES.PLCT_RENEWAL_NUMBER , 
	RES.PLCT_RATE_DAY_PROJ , 
	RES.ACTUAL_SALARY,
  RES.ACCOUNT_ID_LDS,
  RES.ACCOUNT_ID_MCH,
	RES.CONSULTANT_ID_LDS,
	RES.CONSULTANT_ID_MCH
  );

END IF;
END LOOP;
CLOSE CUR;
END SPR_CLEAN_ERR_PROJECT;

--EXECUTING PROCEDURE-----------------------------------
BEGIN 
SPR_CLEAN_ERR_PROJECT;
END
