DROP TABLE STG_CONSULTANT;
CREATE TABLE  "STG_CONSULTANT" 
   (	
   "CONSULTANT_KEY" NUMBER NOT NULL ENABLE, 
	"CONSULTANT_ID_LDS" NUMBER  , 
	"CONSULTANT_ID_MCH" NUMBER , 
	"CONSULTANT_NAME" VARCHAR2(20), 
	"CONSULTANT_POSTCODE" VARCHAR2(100), 
	"HIGHEST_QUALIFICATION" NUMBER, 
	"CONSULTANT_REGISTERED" DATE, 
	"CONSULTANT_SKILL" VARCHAR2(30), 
	"PREFERRED_ROLE" VARCHAR2(30),
	CONSTRAINT "PK_STAGING_CONSULTANT_KEY" PRIMARY KEY ("CONSULTANT_KEY") ENABLE
   ) ;
   
 -- ALTER TABLE ST_CONSULTANT ADD  CONSTRAINT "PK_STAGING_CONSULTANT_KEY" PRIMARY KEY ("CONSULTANT_KEY");

CREATE SEQUENCE   "STAGING_CONSULTANT_SEQ"  
INCREMENT BY 1 
START WITH 181 
CACHE 20 
NOORDER  
NOCYCLE ;

CREATE OR REPLACE TRIGGER  "STAGING_CONSULTANT_TRIGGER_2"
 before insert on STG_CONSULTANT
for each row
begin
:new.CONSULTANT_KEY:=STAGING_CONSULTANT_SEQ.NEXTVAL;
end;

ALTER TRIGGER  "STAGING_CONSULTANT_TRIGGER" ENABLE;

-----------------------------------------------------------------------------------------------
create or replace PROCEDURE PL_CONSULTANT_LDS
IS
BEGIN
INSERT INTO STG_CONSULTANT 
 select
  STAGING_CONSULTANT_SEQ.NEXTVAL,
  CONSULTANT_ID,
  NULL,
  CON_NAME,
  CON_POSTCODE,
  HIGHEST_QUAL,
  CON_REGISTERED,
  NULL,
  NULL
 from LDS_CONSULTANT;
END PL_CONSULTANT_LDS;

begin
PL_CONSULTANT_LDS;
end;
--------------------------------------------------------------------------------------------------
create or replace PROCEDURE PL_CONSULTANT_MCH
iS 
BEGIN
 insert INTO STG_CONSULTANT 
 select
STAGING_CONSULTANT_SEQ.NEXTVAL,
NULL,
CONSULTANT_ID,
CON_NAME,
CON_POSTCODE,
HIGHEST_QUAL,
DATE_REGISTERED,
CON_SKILL,
PREFERRED_ROLE
from MCH_CONSULTANT;
END PL_CONSULTANT_MCH;

BEGIN
 PL_CONSULTANT_MCH;
END;

SELECT COUNT(*) FROM ST_CONSULTANT;
